### PR TITLE
layout fix and realtime color updates

### PR DESCRIPTION
**Pull request by Akshay090**

### CODE REVIEW

**Comment by khalby786** [comment]
Wow, looks good to me, will be merging this pull request very soon and thanks for contributing!

**Comment by Akshay090** [comment]
Thanks. I tried vue for first time in this project, enjoyed it. ✨

**Comment by khalby786** [comment]
Ah, I thought so because you added a `@load` event to load the canvas automatically although it is being triggered by the `mounted` event in the Vue instance (similar to @load).

**Comment by khalby786** [comment]
And the new styling is awesome, thanks again!

**Pull request merged**
